# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
