# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20171021_1817'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_books',
            field=models.ManyToManyField(through='books.Favourite', to='books.Book'),
        ),
    ]
