# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171106_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created',)},
        ),
    ]
