# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='question',
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Followed'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('E', 'Edited Article'), ('S', 'Also Commented'), ('I', 'Image Liked'), ('N', 'Image Commented'), ('R', 'Review Liked')], max_length=1),
        ),
    ]
