# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_likes'),
        ('activities', '0002_auto_20171207_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Review'),
        ),
    ]
