# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.AddField(
            model_name='favourite',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_from_set', to='users.Profile'),
        ),
    ]
