# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date',)},
        ),
    ]
