# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='users_like',
        ),
    ]
