# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_review_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='user',
        ),
    ]
