# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180105_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
