# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180110_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published',
            new_name='first_published',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page_number',
            new_name='page_count',
        ),
        migrations.AddField(
            model_name='book',
            name='original_language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
