# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tags',
            new_name='genres',
        ),
    ]
