# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 08:19
from __future__ import unicode_literals

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20180125_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Genre'),
        ),
    ]
