# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20180126_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
